import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

/// Firebase Service
/// Handles Firebase initialization and provides access to Firebase instances
class FirebaseService {
  static FirebaseService? _instance;
  
  FirebaseService._();
  
  static FirebaseService get instance {
    _instance ??= FirebaseService._();
    return _instance!;
  }

  bool _isInitialized = false;
  
  /// Initialize Firebase for the current platform
  Future<void> initialize() async {
    if (_isInitialized) return;
    
    await Firebase.initializeApp(
      // Firebase options will be auto-generated by flutterfire configure
      // For now, we'll use default options which works for web
    );
    
    // Enable offline persistence for Firestore
    FirebaseFirestore.instance.settings = const Settings(
      persistenceEnabled: true,
      cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
    );
    
    _isInitialized = true;
  }
  
  /// Get Firebase Auth instance
  FirebaseAuth get auth => FirebaseAuth.instance;
  
  /// Get Firestore instance
  FirebaseFirestore get firestore => FirebaseFirestore.instance;
  
  /// Check if Firebase is initialized
  bool get isInitialized => _isInitialized;
}
