// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOfMdtJcfec0Duswsv2OPXEmpAa-smPQI',
    appId: '1:917815174581:web:a0512e82f48690479065fc',
    messagingSenderId: '917815174581',
    projectId: 'gullwing-df99d',
    authDomain: 'gullwing-df99d.firebaseapp.com',
    storageBucket: 'gullwing-df99d.firebasestorage.app',
    measurementId: 'G-XMXY9R1SNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3dBhsrgYz2VKgd85DLeZT8EIZtEddjT8',
    appId: '1:917815174581:android:afa92b81901ac8a09065fc',
    messagingSenderId: '917815174581',
    projectId: 'gullwing-df99d',
    storageBucket: 'gullwing-df99d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWV3z7O_A-cuRNnGpkjzWxcLRUorOyal0',
    appId: '1:917815174581:ios:75ae7aab797697039065fc',
    messagingSenderId: '917815174581',
    projectId: 'gullwing-df99d',
    storageBucket: 'gullwing-df99d.firebasestorage.app',
    iosBundleId: 'com.clipsync.clipsync',
  );
}
